# Workflow to configure with cmake and build with gcc-10

name: Build with gcc-11 (Mac)

on:
  push: 
    branches: [ master ]
  workflow_dispatch: 

#  pull_request:
#    branches:
#      - '*'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

jobs:
  build:

    runs-on: macos-latest

    steps:

    - name: Checkout NWhy
      uses: actions/checkout@v2
      with:
        path: NWhy

# The macos image evidently has gcc-11 and cmake 3.22 pre-installed
    - name: prep
      run: |
        brew update
        brew install tbb
    - name: cmake
      run: |
        cd NWhy
        mkdir build
        cd build
        export TBBROOT=/opt/intel/oneapi/tbb/latest
        cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_CXX_COMPILER=g++-11 -DNW_GRAPH_BUILD_DOCS=OFF -DNW_GRAPH_BUILD_TESTS=ON
    - name: make
      run: |
        cd NWhy/build
        make -j -k
    - name: run_test
      run: |
        cd NWhy/build/test/
        make test